services:

    Mpp\UniversignBundle\Controller\CallbackController:
        tags: ['controller.service_arguments']
        arguments:
            - '@event_dispatcher'

    Mpp\UniversignBundle\Requester\XmlRpcRequester:
        arguments:
            - '@logger'
            - '@router'
            - '%mpp_universign.entrypoint%'
            - '%mpp_universign.options%'

    Mpp\UniversignBundle\Requester\RequesterInterface: '@Mpp\UniversignBundle\Requester\XmlRpcRequester'