services:

    Mpp\UniversignBundle\Requester\XmlRpcRequester:
        arguments:
            - '%mpp_universign.entrypoint_url%'

    Mpp\UniversignBundle\Requester\RequesterInterface: '@Mpp\UniversignBundle\Requester\XmlRpcRequester'