services:

    Mpp\UniversignBundle\Controller\CallbackController:
        tags: ['controller.service_arguments']
        arguments:
            - '@logger'
            - '@event_dispatcher'

    Mpp\UniversignBundle\Requester\Signer:
        arguments:
            - '@logger'
            - '@router'
            - '%mpp_universign.entrypoint%'
            - '%mpp_universign.options%'

    Mpp\UniversignBundle\Requester\RegistrationAuthority:
        arguments:
            - '@logger'
            - '@router'
            - '%mpp_universign.entrypoint%'
            - '%mpp_universign.options%'

    Mpp\UniversignBundle\Requester\SignerInterface: '@Mpp\UniversignBundle\Requester\Signer'
    Mpp\UniversignBundle\Requester\RegistrationAuthorityInterface: '@Mpp\UniversignBundle\Requester\RegistrationAuthority'